### ISSUE TITLE
Add music player

### ISSUE THREAD

**Issue by SteveALee** [AlwaysInMind/aim-web-app#60]
Perhaps spotify?

However youtube playlists make good music selections so is there a need for a separate player?

**Comment by SteveALee** [comment]
YouTube has masses of music, often enhanced with videos (though often just album artwork). It seem reasonable to use this for music as well as videos. The demo shows an example under videos option.

* Supporter experience is good - same login as google photos and easy to add photos to playlists
* Can add a favourites option and probably more a You tube has rich feature set suitable for media 
* Need to decide how presented to user. 
  * Show videos?
  * extra top level button in Activities screen so both video or music. Or just one button for both.  

@Dreadthis do you have any thoughts

**Comment by Dreadthis** [comment]
Hi Steve

Really great idea - if it's easy to navigate for the user I would go  
for the music with video  when clicking on music

Hope they stay on Always in Mind site and don't get hijacked by  
YouTube and then struggle to navigate back to Always in Mind

Cheers
Dave


Quoting Steve Lee <notifications@github.com>:

**Comment by SteveALee** [comment]
> Hope they stay on Always in Mind site and don't get hijacked by YouTube and then struggle to navigate back to Always in Mind

Yes all safe in that respect - take a look at the [demo](https://alwaysinmind.now.sh).

While we have to use the embedded youtube player to show the vidoes this appears to be transparent and I disbaled all the controls for now (may add for more complex 'levels'). We don't even see adverts!
